import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import {initDatabase,recordVisit,readCounts,koreaDay} from './core.mjs';
const db=new DatabaseSync(':memory:');
const sql={exec(query,...args){const s=db.prepare(query);return query.startsWith('SELECT')?s.all(...args):(s.run(...args),[]);}};
const storage={sql,transactionSync(fn){db.exec('BEGIN');try{const result=fn();db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}};
initDatabase(sql);
const beforeMidnight=new Date('2026-09-20T14:59:59Z'),afterMidnight=new Date('2026-09-20T15:00:00Z');
assert.equal(koreaDay(beforeMidnight),'2026-09-20');assert.equal(koreaDay(afterMidnight),'2026-09-21');
assert.deepEqual(recordVisit(storage,'browser-a',beforeMidnight),{day:'2026-09-20',total:1,today:1});
assert.equal(recordVisit(storage,'browser-a',beforeMidnight).total,1);
assert.equal(recordVisit(storage,'browser-b',beforeMidnight).today,2);
assert.deepEqual(readCounts(sql,'2026-09-21'),{day:'2026-09-21',total:2,today:0});
assert.deepEqual(recordVisit(storage,'browser-a',afterMidnight),{day:'2026-09-21',total:3,today:1});
assert.equal(recordVisit(storage,'browser-a',afterMidnight).total,3);
initDatabase(sql);assert.equal(readCounts(sql,'2026-09-21').total,3);
for(let i=0;i<100;i++)recordVisit(storage,'browser-'+i,afterMidnight);
assert.equal(readCounts(sql,'2026-09-21').total,103);
assert.equal([...sql.exec('SELECT count FROM daily WHERE day=?','2026-09-20')][0].count,2);
console.log('PASS duplicate refresh, independent browsers, KST midnight, persisted totals, daily history');
